[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py makemigrations",
  "python manage.py migrate",
  "python manage.py collectstatic --noinput"
]
