[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py runserver 0.0.0.0:$PORT"

[[services]]
name = "web"
run = "python manage.py runserver 0.0.0.0:$PORT"

[[services]]
name = "qcluster"
run = "python manage.py qcluster"