# Generated by Django 5.2.6 on 2025-10-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='fixed_rate',
        ),
        migrations.AddField(
            model_name='employee',
            name='custom_base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='fixed_rate',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
