# Generated by Django 5.2.6 on 2025-09-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayrollRecord',
            new_name='Payment',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='payroll_record',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='PayrollDetail',
        ),
    ]
