# Generated by Django 5.2.6 on 2025-10-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='shutdown_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
