# Generated by Django 5.2.6 on 2025-10-19 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campaign_shutdown_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='employees',
        ),
        migrations.AddField(
            model_name='employee',
            name='campaigns',
            field=models.ManyToManyField(blank=True, related_name='employees', to='core.campaign'),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign where the employee is currently active.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_employees', to='core.campaign'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
