# Generated by Django 5.2.6 on 2025-09-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_payrollrecord_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
