# Generated by Django 5.2.6 on 2025-10-07 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_position_fixed_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_supervisor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor directo del empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='core.employee'),
        ),
    ]
