# Generated by Django 5.2.6 on 2025-09-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
