# Generated by Django 5.2.6 on 2025-10-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_is_supervisor_employee_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_it',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
