# Generated by Django 5.2.6 on 2025-09-30 02:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_employee_postal_code_employee_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='identification',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
