# Generated by Django 5.2.6 on 2025-10-10 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_is_it'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
