# Generated by Django 5.2.6 on 2025-11-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='break_duraction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='lunch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
