# Generated by Django 5.2.6 on 2025-09-30 02:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment_identification_alter_payment_pay_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='identification',
        ),
        migrations.AddField(
            model_name='employee',
            name='identification',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
