# Generated by Django 5.2.6 on 2025-09-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_payment_identification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='fixed_rate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='hour_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
