# Generated by Django 5.2.6 on 2025-09-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_position_fixed_rate_position_hour_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
