# Generated by Django 5.2.6 on 2026-01-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_relatedfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='isr_to_apply',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='monthly_gross_accumulated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='monthly_isr_calculated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payperiod',
            name='month',
            field=models.IntegerField(blank=True, help_text='Month number (1-12)', null=True),
        ),
        migrations.AddField(
            model_name='payperiod',
            name='period_type',
            field=models.CharField(choices=[('first_half', 'First Half of Month'), ('second_half', 'Second Half of Month'), ('monthly', 'Monthly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='payperiod',
            name='year',
            field=models.IntegerField(blank=True, help_text='Year', null=True),
        ),
    ]
