# Generated by Django 5.2.6 on 2025-10-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_campaign_base_salary_campaign_break_duraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bonus_type',
            field=models.CharField(blank=True, choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='bonus_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='campaign', to='core.employee'),
        ),
    ]
