# Generated by Django 5.2.6 on 2025-10-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_campaign_bonus_type_campaign_bonus_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='break_duraction',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='lunch',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
