# Generated by Django 5.2.6 on 2025-12-17 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_relatedfamily'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shift_type', models.CharField(choices=[('morning', 'Morning Shift'), ('afternoon', 'Afternoon Shift'), ('evening', 'Evening Shift'), ('night', 'Night Shift'), ('rotating', 'Rotating Shift')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('expected_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('break_duration_minutes', models.IntegerField(default=15, help_text='Duration of each break in minutes')),
                ('break_count', models.IntegerField(default=2, help_text='Number of allowed breaks')),
                ('lunch_duration_minutes', models.IntegerField(default=60, help_text='Lunch duration in minutes')),
                ('first_break_time', models.TimeField(blank=True, help_text='Suggested time for first break', null=True)),
                ('second_break_time', models.TimeField(blank=True, help_text='Suggested time for second break', null=True)),
                ('lunch_time', models.TimeField(blank=True, help_text='Suggested lunch time', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_overtime', models.BooleanField(default=True)),
                ('max_overtime_hours', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('color_code', models.CharField(default='#3B82F6', help_text='Color for calendar display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, help_text='Specific campaign for this shift (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campaign')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='BreakSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('break_type', models.CharField(choices=[('break', 'Break'), ('lunch', 'Lunch')], max_length=10)),
                ('scheduled_start_time', models.TimeField()),
                ('scheduled_end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('was_taken', models.BooleanField(default=False)),
                ('actual_start_time', models.TimeField(blank=True, null=True)),
                ('actual_end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_schedules', to='core.employee')),
            ],
            options={
                'ordering': ['date', 'scheduled_start_time'],
                'unique_together': {('employee', 'date', 'break_type', 'scheduled_start_time')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave empty for an indefinite schedule', null=True)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('custom_start_time', models.TimeField(blank=True, null=True)),
                ('custom_end_time', models.TimeField(blank=True, null=True)),
                ('custom_break_duration', models.IntegerField(blank=True, null=True)),
                ('custom_lunch_duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_employees', to='workforce.shift')),
            ],
            options={
                'ordering': ['-start_date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'start_date', 'end_date'], name='workforce_e_employe_c1e376_idx'), models.Index(fields=['status', 'start_date'], name='workforce_e_status_86e94d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick_leave', 'Sick Leave'), ('personal', 'Personal Day'), ('unpaid', 'Unpaid Leave'), ('bereavement', 'Bereavement'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('is_paid', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_requests', to='core.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='workforce_t_employe_14a03b_idx'), models.Index(fields=['start_date', 'end_date'], name='workforce_t_start_d_ade9eb_idx')],
            },
        ),
    ]
