# Generated by Django 5.2.6 on 2025-12-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeschedule',
            name='custom_break_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeschedule',
            name='custom_first_break_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeschedule',
            name='custom_lunch_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeschedule',
            name='custom_second_break_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
