# Generated by Django 5.2.6 on 2025-12-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_employeeschedule_custom_break_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
