# Generated by Django 5.2.6 on 2025-10-20 20:39

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_campaign_employees_employee_campaigns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('absent', 'Ausente'), ('leave', 'Permiso')], default='active', max_length=20)),
                ('total_work_time', models.DurationField(default=datetime.timedelta(0))),
                ('total_break_time', models.DurationField(default=datetime.timedelta(0))),
                ('total_lunch_time', models.DurationField(default=datetime.timedelta(0))),
                ('productive_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('break_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='core.employee')),
            ],
            options={
                'ordering': ['-date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('work', 'Trabajo'), ('break', 'Break'), ('lunch', 'Almuerzo'), ('training', 'Capacitación'), ('meeting', 'Reunión'), ('technical', 'Problema Técnico')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('auto_created', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campaign')),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.workday')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='workday',
            index=models.Index(fields=['date', 'status'], name='attendance__date_31fe48_idx'),
        ),
        migrations.AddIndex(
            model_name='workday',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_10fbab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workday',
            unique_together={('employee', 'date')},
        ),
    ]
