# Generated by Django 5.2.6 on 2025-11-08 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysession',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='adjustment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='adjustment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='is_adjusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='original_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='original_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='adjustment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workday',
            name='last_adjusted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workday',
            name='last_adjustment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
