# Generated by Django 5.2.6 on 2025-11-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysession',
            name='session_type',
            field=models.CharField(choices=[('work', 'Working'), ('break', 'Break'), ('lunch', 'Almuerzo'), ('training', 'Training'), ('meeting', 'Meeting'), ('technical', 'Technical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workday',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('absent', 'Absent'), ('leave', 'On Leave')], default='active', max_length=20),
        ),
    ]
