# Generated by Django 5.2.6 on 2025-11-08 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_activitysession_adjusted_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workday',
            old_name='adjustment_count',
            new_name='adjustment_count_field',
        ),
    ]
