# Generated by Django 5.2.6 on 2025-10-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_agentstatus_statusschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentstatus',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
