# Generated by Django 5.2.6 on 2025-11-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_adjustment_count_workday_adjustment_count_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='adjustment_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workday',
            name='last_adjustment_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
