# Generated by Django 5.2.6 on 2025-10-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_agentstatus_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentstatus',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
