# Generated by Django 5.2.6 on 2025-10-07 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_agentstatus_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentstatus',
            options={'ordering': ['end_time'], 'verbose_name': 'Agent Status', 'verbose_name_plural': 'Agent Statuses'},
        ),
    ]
