# Generated by Django 5.2.6 on 2025-11-23 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_workday_adjustment_history_and_more'),
        ('core', '0005_paymentdetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workdays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workday',
            name='holiday_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='workday',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workday',
            name='night_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='workday',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='workday',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workday',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workday',
            name='regular_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='workday',
            name='regular_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workday',
            name='regular_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workday',
            name='total_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workday',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('absent', 'Absent'), ('leave', 'On Leave'), ('regular_hours', 'Regular hours'), ('holyday', 'Holy Day')], default='regular_hours', max_length=20),
        ),
        migrations.AddIndex(
            model_name='workday',
            index=models.Index(fields=['is_approved', 'date'], name='attendance__is_appr_463a2f_idx'),
        ),
    ]
