# Generated by Django 5.2.6 on 2025-10-11 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_agentstatus_options'),
        ('core', '0006_campaign_delete_cliant_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstatus',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_statuses', to='core.campaign'),
        ),
    ]
