# Generated by Django 5.2.6 on 2025-12-10 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_occurrence'),
        ('core', '0006_alter_payment_options_payment_calculated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
    ]
