# Generated by Django 5.2.6 on 2025-12-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_occurrence_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='occurrence_type',
            field=models.CharField(choices=[('technical_issues', 'Technical Issues'), ('call_drop', 'Call Drop'), ('Bath_room', 'Bath room')], max_length=50),
        ),
    ]
