# Generated by Django 5.2.6 on 2025-12-16 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_occurrence_occurrence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 12, 16, 19, 38, 35, 122407)),
            preserve_default=False,
        ),
    ]
