# Generated by Django 5.2.6 on 2025-12-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_occurrence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='night_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workday',
            name='night_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workday',
            name='overtime_hours_135',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas extras 44-68h (35% premium)', max_digits=5),
        ),
        migrations.AddField(
            model_name='workday',
            name='overtime_hours_200',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas extras >68h (100% premium)', max_digits=5),
        ),
        migrations.AddField(
            model_name='workday',
            name='overtime_pay_135',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workday',
            name='overtime_pay_200',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workday',
            name='overtime_rate_135',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workday',
            name='overtime_rate_200',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workday',
            name='night_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas trabajadas 9PM-7AM (15% premium)', max_digits=5),
        ),
    ]
