"""
Django settings for payroll project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
from django.urls import reverse_lazy
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

from dotenv import load_dotenv

load_dotenv()

DEBUG = True

BASE_URL = os.getenv("BASE_URL")

ALLOWED_HOSTS = [
    'payroll-production-890f.up.railway.app',
    'localhost',
    '127.0.0.1'
]

CSRF_TRUSTED_ORIGINS = [
    'https://*.up.railway.app',
    'http://localhost:8000'
]


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'crispy_forms',
    'crispy_bootstrap5',
    'django.contrib.humanize',
    'import_export',
    'django_q',
    'pwa',
    'django_user_agents',
    'rest_framework',
    'corsheaders',
    
    'core',
    'payroll',
    'accounts',
    'attendance',
    'hhrr',
    'payment',
    'it_management'
]


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'accounts.middleware.DeviceAuthenticationMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
    'core.middleware.block_mobile.BlockMobileMiddleware'
]


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 1000,  
}

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'payroll.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.employee_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'payroll.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv("DATABASE_PUBLIC_URL")
    )
}


## Redus Configuration
REDIS_PUBLIC_URL = os.getenv("REDIS_PUBLIC_URL")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

Q_CLUSTER = {
    'name': 'DjangoQ',
    'workers': 4,
    'recycle': 500,
    'timeout': 300,
    'retry': 620,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',
    'catch_up': False, 
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [

    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',

]

# ==============================================================================
# DJANGO-ALLAUTH CONFIGURATION - OPTIMIZADO PARA INVITACIONES
# ==============================================================================

# SESIONES
SESSION_COOKIE_AGE = 1209600  # 2 semanas
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CONFIGURACIONES BÁSICAS Y SEGURIDAD
ACCOUNT_AUTHENTICATION_METHOD = 'email'           # Login solo con email
ACCOUNT_EMAIL_REQUIRED = True                     # Email obligatorio
ACCOUNT_USERNAME_REQUIRED = False                 # NO requerir username (solo email)
ACCOUNT_UNIQUE_EMAIL = True                       # Email único por cuenta
ACCOUNT_EMAIL_VERIFICATION = 'none'               # SIN verificación de email (flujo rápido)

# VALIDACIONES DE USUARIO (si usas username)
ACCOUNT_USERNAME_MIN_LENGTH = 3
ACCOUNT_USERNAME_BLACKLIST = ['admin', 'administrator', 'moderator', 'root', 'superuser']
ACCOUNT_PRESERVE_USERNAME_CASING = False
ACCOUNT_ALLOW_REGISTRATION = True 

# CONFIGURACIÓN DE EMAIL
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[Payroll] '
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3        
ACCOUNT_EMAIL_CONFIRMATION_HMAC = True
ACCOUNT_MAX_EMAIL_ADDRESSES = 1

# Deshabilitar emails automáticos (solo enviaremos el de invitación)
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = None
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = None

# COMPORTAMIENTO DE SESIONES Y REDIRECCIONES
ACCOUNT_SESSION_REMEMBER = True                   # Recordar sesión
ACCOUNT_LOGOUT_ON_GET = False                     # Confirmar logout
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False       # No aplica sin verificación
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True            # Auto-login después de reset

# URLs DE REDIRECCIÓN (el adapter las sobrescribe cuando es necesario)
ACCOUNT_LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'
ACCOUNT_SIGNUP_REDIRECT_URL = None  # Manejado por el adapter

# FORMULARIOS Y ADAPTERS PERSONALIZADOS
ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CustomSignupForm',
}

ACCOUNT_ADAPTER = 'accounts.adapters.CustomAccountAdapter'

# LIMITES DE SEGURIDAD
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',    # 5 intentos fallidos en 5 minutos
    'signup': '10/1h',         # 10 registros por hora
    'password_reset': '3/1h',  # 3 reseteos de password por hora
}



# ==============================================================================
# DJANGO CORE AUTH CONFIGURATION (Compatibilidad)
# ==============================================================================
LOGIN_URL = '/accounts/login/'                 
LOGIN_REDIRECT_URL = '/'                         
LOGOUT_REDIRECT_URL = '/accounts/login/'  

# ==============================================================================
#email backend
# ==============================================================================
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development

# For production:
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'lorf543@gmail.com'
EMAIL_HOST_PASSWORD = 'mgnreflxbqvdykee'
DEFAULT_FROM_EMAIL = 'noreply@helium.com.co'
EMAIL_TIMEOUT = 60






# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Santo_Domingo'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


MEDIA_URL = '/media/'


STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}




# Configuración PWA
PWA_APP_NAME = 'Employee Portal'
PWA_APP_DESCRIPTION = "Employee Management System"
PWA_APP_THEME_COLOR = '#2c3e50'
PWA_APP_BACKGROUND_COLOR = '#34495e'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/icons/web-app-manifest-192x192.png',
        'sizes': '192x192'
    },
    {
        'src': '/static/icons/web-app-manifest-512x512.png',
        'sizes': '512x512'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/icons/icon-160x160.png',
        'sizes': '160x160'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/images/splash-640x1136.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
PWA_APP_DEBUG_MODE = False

# Service Worker
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static/js', 'serviceworker.js')